function infoContent () {

    // ` this is a "back tick". Use it to define multi-line strings in JavaScript.
    var content = `
      <h3>Info</h3>
      <p>
        This is where I would put some general information. This text
        is also generated by code and injected into the page HTML.
      </p>
    `;
    
    var ele = document.createElement("div");
    ele.innerHTML = content;
    return ele; 
}